### ISSUE TITLE
JSON Table Schema in MessyTables

### ISSUE THREAD

**Issue by pwalsh** [okfn/messytables#135]
In light of https://github.com/mk270/json-table-schema-python/issues/4 and https://github.com/okfn/messytables/pull/131, I want to talk about about JSON Table Schema.

* We recently wrote a new JSON Table Schema library: https://github.com/okfn/jsontableschema-py
  * It is much more in line with the JSON Table Schema spec
  * It is used in a number of projects, and is therefore guaranteed to keep under development
  * It is currently published on PyPI under `jtskit`
* A couple of weeks ago, I took over the package for json-table-schema on PyPI from @mk270 
* The plan is, in the next couple of weeks, to start publishing "jtskit" under the `json-table-schema` package

**Comment by davidread** [comment]
The question is, are is a reasonable chance of breaking changes affecting messytables? If so we should add an upper-limit on the json-table-schema version in setup.py, for the sake of future messytables releases.

**Comment by pwalsh** [comment]
@davidread there should be an upper-limit on  `json-table-schema` in any event (and other deps., as I made the case for in #144).

For your question, in this case: yes, the new code is a completely different API. 

I think the question is more, then, does anyone want to fix JTS support in the current version of messy tables? if yes, the effort should be made to support the new lib, which actually implements most of the spec, unlike the current dependency in messytables. If it is not important, then, I strongly suggest pinning the dependency at the last version of the old codebase.

I've been talking with @pudo about MT2 ([ref.](https://github.com/okfn/tabulator-py/issues/1) and [ref.](https://github.com/okfn/messytables/issues/142)) and any code there would certainly use the new lib in any event.

**Comment by pwalsh** [comment]
Version has been pinned to the (very) old jts lib. We'd have to see more interest to make the changes required for the more up-to-date lib that OKI has. And, once @pudo brings in [`typecast`](https://github.com/okfn/messytables/pull/155) it will probably be enough for the current use cases around messytables.
