### ISSUE TITLE
Externalize PDF support?

### ISSUE THREAD

**Issue by pudo** [okfn/messytables#137]
Hi all, I only returned to looking at messytables after a good while today (see #136). It strikes me that PDF parsing support is a deeply absurd thing to try and do in a utility library like messytables.

I've taken half a dozen table-containing PDFs now to throw them at the PDF tool and none of them gave me a useful result.

On the other hand, having whacky features like this makes messytables feel bloated and heavyweight. 

I wonder if there would be a strong argument against building an entry_points mechanism and then putting the PDF parser in it's own module? That would then also manage dependencies properly, instead of soft-failing upon call.

**Comment by davidread** [comment]
@pudo Agreed. Finally got around to doing this. Can you or @StevenMaude review/approve? https://github.com/okfn/messytables/pull/186

**Comment by davidread** [comment]
Removed in #186
